version: '3.8'

services:
  # Neo4j database
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_DATABASE=neo4j
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - neo4j
    restart: unless-stopped

  # Frontend React app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: